theme: jekyll-theme-minimal
title: Seth Stamper's Page
description: Hello! My name is Seth Stamper. I'm a senior Computer Science student at Clemson University with a Minor in Cybersecurity. I love coding, hiking, and playing video games.
author: Seth Stamper